onboarding = false

[theme]
name = "dracula"

    [theme.custom]
    overlay0 = "#8be9fd"

[keys]
prefix = "ctrl+a"
split_vertical = "prefix+\\"
detach = "prefix+d"
navigate_workspace_up = "k"
navigate_workspace_down = "j"
rename_tab = "prefix+,"

[ui]
agent_panel_sort = "spaces"
